[package]
name = "cidno" #"cg7id"
version = "4.2.0" #"4.00"
authors = ["Karl Vincent Pierre Bertin <karl.v.p.bertin@gmail.com>", "Karl Thomas George West <karl.t.g.west@gmail.com>"]
edition = "2021"
#rust-version =
description = "An ID number calculator."
#documentation = ""
readme = "README.md"
repository = "https://github.com/kvpb/cidno" #"https://github.com/kvpb/cg7id"
#license = "BSD-3-Clause"
license-file = "LICENSE"
keywords = ["non-random", "random", "generation", "i", "1", "g1", "iii", "3", "g3", "vii", "7", "g7", "trainer", "id", "g7id", "tid", "idno", "g7tid", "secret", "sid", "g7sid", "number", "shiny", "value", "tsv", "residual", "trv", "forward", "reverse", "backward", "calculator"]

[dependencies]
#libc = "^0.2"
#cxx = "^1.0"
rand = "^0.8"
libm = "^0.2"
num-traits = "^0.2"
#cg7tid = { path = "./src/cg7tid/" }
#bcg7tid = { path = "./src/bcg7tid/" }
#rcg7tid = { path = "./src/rcg7tid/" }

#[build-dependencies]
#cxx-build = "1.0"

[profile.dev]
opt-level = 0
debug = true
overflow-checks = false
incremental = true

[profile.release]
opt-level = 3
debug = false
overflow-checks = true
lto = true
panic = "abort"

#	Cargo.toml
#	CIDNo (IDNo Calculator)
#
#	Karl V. P. B. `kvpb`	AKA Karl Thomas George West `ktgw`
#	+33 A BB BB BB BB		+1 (DDD) DDD-DDDD
#	local-part@domain
#	https://twitter.com/ktgwkvpb
#	https://github.com/kvpb
